export const articlesItem: string
export const container: string
export const content: string
export const tags: string
export const title: string
export const buttons: string
export const personInfo: string
export const description: string
export const tag: string
export const avatar: string
