export const createArticle: string
export const logOut: string
export const nav: string
export const navContent: string
export const navLinks: string
export const personInfo: string
export const userName: string
export const signUp: string
export const avatar: string
